---
# tasks file for ansible-role-logrotate

- name: Set OS dependent variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install lograte
  include_tasks: install.yml

- name: setup logrotate
  include_tasks: setup.yml
